[workspace]
resolver = "3"
members = [
    "medbook-events",
    "medbook-inventoryservice",
    "medbook-ordersservice",
    "medbook-paymentservice",
    "medbook-deliveryservice",
    "medbook-userservice",
]
